server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cajadeahorro
    username: jacobguzmanacosta
    password: password
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
